---
title: "UpsupervisedLearning"
author: "Bogdan Abaev"
date: "3/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE, include = TRUE}
library(plotROC) # required to use geom_roc
library(kernlab)
library(caret)
library(mlbench) # contains a number of benchmark machine learning data sets
library(tidyr)
library(gbm)
library(glmnet)
library(randomForest)
library(nnet)


#question 1 
data(BostonHousing)
set.seed(22)
test.id <- createDataPartition(BostonHousing$chas, p = .2, list = FALSE)
fit.control <- trainControl(method = "repeatedcv", number = 5, repeats = 10)
train.data <- BostonHousing[-test.id,]
test.data <- BostonHousing[test.id,]

prop.table(table(train.data$chas))
glmnet.fit <- train(tax ~ ., data = train.data, method = "glmnet", trControl = fit.control)

# question 2 
#The best parameters are:  alpha=0.10 lambda=0.3052749 with RMSE=58.17627
# Gradient boosting machine's best performace was at n.trees=150  with RMSE=40.63623,
# so seems like gbm works better.

#question 3 
set.seed(7)
lm.fit <- train(tax ~ ., data = train.data, method = "lm", trControl = fit.control)
set.seed(7)
gbm.fit <- train(tax ~ ., data = train.data, method = "gbm", trControl = fit.control, verbose = FALSE)

resamps <- resamples(list(GBM = gbm.fit,
                           LM = lm.fit, GLM=glmnet.fit))
 resamps2 <- gather(resamps$values, key = "Var", value = "Val", 2:ncol(resamps$values))
 resamps2 <- separate(resamps2, col = "Var", into = c("Model", "Metric"), sep = "~")
 ggplot(resamps2, aes(x = Model, y = Val)) + geom_boxplot() + facet_wrap(~ Metric, scales = "free")
 
 
#question 4 
data("spam")
spam = spam[complete.cases(spam),]
set.seed(14)
train.id = sample(1:nrow(spam),size= .8*nrow(spam))
train.spam = data.frame(spam[train.id,])
test.spam = data.frame(spam[-train.id,])
fit.control = trainControl(method="repeatedcv",number = 5, repeats=10, classProbs=TRUE, savePredictions = TRUE, summaryFunction = twoClassSummary)

set.seed(7)
glm.fit <- train(type ~ ., data = test.spam, method = "glm", family = "binomial", trControl = fit.control, metric = "ROC")

ggplot(glm.fit$pred, aes(d = obs, m = spam)) +
  geom_roc() + 
  coord_equal() +
  style_roc()
 
#question 5 
data("Vehicle")
set.seed(22)
test.id <- sample(1:nrow(Vehicle), size = .2*nrow(Vehicle))
train.data <- Vehicle[-test.id,]
test.data <- Vehicle[test.id,]
fit.control <- trainControl(method = "repeatedcv", number = 5, repeats = 10)
set.seed(7)
lm.fit <- train(Comp ~ ., data = train.data, method = "lm", trControl = fit.control)
gbm.grid <- expand.grid(interaction.depth = c(1, 3, 5), 
                        n.trees = (1:10)*100, 
                        shrinkage = 0.1,
                        n.minobsinnode = 20)
set.seed(7)
gbm.fit2 <- train(Comp ~ ., data = train.data, method = "gbm", trControl = fit.control, verbose = FALSE, tuneGrid = gbm.grid)
set.seed(7)
bag.fit =  train(Comp ~ ., data = train.data, method = "glmboost", trControl = fit.control)
resamps <- resamples(list(BAG = bag.fit, LM = lm.fit, GBM = gbm.fit2))
resamps2 <- gather(resamps$values, key = "Var", value = "Val", 2:ncol(resamps$values))
resamps2 <- separate(resamps2, col = "Var", into = c("Model", "Metric"), sep = "~")
ggplot(resamps2, aes(x = Model, y = Val)) + geom_boxplot() + facet_wrap(~ Metric, scales = "free")


#question 6
data("Zoo")
set.seed(22)
test.id <- sample(1:nrow(Zoo), size = .2*nrow(Zoo))
train.data <- Zoo[-test.id,]
test.data <- Zoo[test.id,]
fit.control <- trainControl(method = "repeatedcv", number = 5, repeats = 10)
set.seed(7)
nn.fit <- train(type ~ ., data = train.data, method = "nnet", trControl = fit.control, verbose = FALSE, trace = FALSE)
set.seed(7)
lvq.fit =  train(type ~ ., data = train.data, method = "lvq", trControl = fit.control)
set.seed(7)
mlp.fit <- train(type ~ ., data = train.data, method = "mlp", trControl = fit.control)
resamps <- resamples(list(NN = nn.fit, LVQ = lvq.fit, MLP = mlp.fit))
resamps2 <- gather(resamps$values, key = "Var", value = "Val", 2:ncol(resamps$values))
resamps2 <- separate(resamps2, col = "Var", into = c("Model", "Metric"), sep = "~")
ggplot(resamps2, aes(x = Model, y = Val)) + geom_boxplot() + facet_wrap(~ Metric, scales = "free")
 
```





